CREATE DATABASE example
	DEFAULT CHARACTER SET utf8;
USE example;

CREATE TABLE tasks (
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	status INT NOT NULL,
	person VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

